import { Text, View } from "@react-pdf/renderer";
import { styles } from "./medical-report-styles";

interface Props {
  createdBy: string;
}

export default function MedicalReportFooter({ createdBy }: Props) {
  return (
    <View style={styles.footer}>
      <Text style={{ fontWeight: "bold", color: "#2563EB" }}>User: {createdBy}</Text>
      <Text>Report generated by AI Medical Voice Agent</Text>
    </View>
  );
}
